[package]
name = "streaming_shape_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
binext = "1.0.0"
eyre = "0.6.12"
image = { version = "0.25.6", default-features = false, features = ["png"] }
squish = "1.0.0"
